name = "KeitaNakamuraRegistry"
uuid = "e90d1bfd-b7d4-478e-ac5a-e1eac89621f4"
repo = "https://github.com/KeitaNakamura/KeitaNakamuraRegistry.git"

[packages]
96e687be-8443-480e-bfb6-9a1bb5ee0d0e = { name = "TesseraeGmsh", path = "T/TesseraeGmsh" }
bf82f66e-8fcd-4ce9-a12d-a25ca77d3b00 = { name = "GmshReader", path = "G/GmshReader" }
cb5f3ba8-f211-439d-a907-3cde74a9b555 = { name = "Grapher", path = "G/Grapher" }
